Add support of context parallelism for versions of VLLM that support it (>= 0.15).
Unfortunately, it currently fails with VLLM 0.15.1 in our env:
  File ".../vllm/v1/worker/gpu_worker.py", line 412, in initialize_from_config
    self.model_runner.initialize_kv_cache(kv_cache_config)
  File ".../vllm/v1/worker/gpu_model_runner.py", line 5874, in initialize_kv_cache
    self.initialize_attn_backend(kv_cache_config)
  File ".../vllm/v1/worker/gpu_model_runner.py", line 5225, in initialize_attn_backend
    check_attention_cp_compatibility(self.vllm_config)
  File ".../vllm/v1/worker/cp_utils.py", line 39, in check_attention_cp_compatibility
    assert layer_impl.supports_pcp, (
AssertionError: PCP requires attention impls' support, but the impl FlashAttentionImpl does not support PCP.